import { CourierOption, FieldDefinition } from '@/types';

export const POPULAR_COURIERS: CourierOption[] = [
  { key: 'AmazonShipping', name: 'Amazon Shipping' },
  { key: 'Amazon', name: 'Amazon' },
  { key: 'APC', name: 'APC' },
  { key: 'Asendia', name: 'Asendia' },
  { key: 'Chronopost', name: 'Chronopost' },
  { key: 'CitySprint', name: 'CitySprint' },
  { key: 'ColisPriveFR', name: 'Colis Prive' },
  { key: 'CollectPlus', name: 'Collect Plus' },
  { key: 'Correos', name: 'Correos' },
  { key: 'DespatchCloud', name: 'Despatch Cloud' },
  { key: 'DeutschePost', name: 'Deutsche Post' },
  { key: 'DGInternational', name: 'DG International' },
  { key: 'DHL', name: 'DHL Express' },
  { key: 'DHLeCommerce', name: 'DHL eCommerce' },
  { key: 'DHLParcelUK', name: 'DHL Parcel UK' },
  { key: 'DHLParcelDE', name: 'DHL Parcel Germany' },
  { key: 'DHLParcelNL', name: 'DHL Parcel Netherlands' },
  { key: 'DHLParcelSpain', name: 'DHL Parcel Spain' },
  { key: 'DHLPoland', name: 'DHL Poland' },
  { key: 'DPD', name: 'DPD' },
  { key: 'DPDLocal', name: 'DPD Local' },
  { key: 'DPDGermany', name: 'DPD Germany' },
  { key: 'DPDIreland', name: 'DPD Ireland' },
  { key: 'DPDNL', name: 'DPD Netherlands' },
  { key: 'DX', name: 'DX' },
  { key: 'DxExpress', name: 'DX Express' },
  { key: 'DxFreight', name: 'DX Freight' },
  { key: 'Evri', name: 'Evri' },
  { key: 'EvriCorporate', name: 'Evri Corporate' },
  { key: 'EvriInternational', name: 'Evri International' },
  { key: 'Fastway', name: 'Fastway' },
  { key: 'Fedex', name: 'FedEx' },
  { key: 'GLSDE', name: 'GLS Germany' },
  { key: 'GLSFR', name: 'GLS France' },
  { key: 'GLSNL', name: 'GLS Netherlands' },
  { key: 'GLSES', name: 'GLS Spain' },
  { key: 'Hermes', name: 'Hermes' },
  { key: 'HermesCorporate', name: 'Hermes Corporate' },
  { key: 'InPost', name: 'InPost' },
  { key: 'Landmark', name: 'Landmark' },
  { key: 'PalletWays', name: 'Palletways' },
  { key: 'Palletforce', name: 'Palletforce' },
  { key: 'Panther', name: 'Panther' },
  { key: 'PostNL', name: 'PostNL' },
  { key: 'RoyalMail', name: 'Royal Mail' },
  { key: 'RoyalMailClickAndDrop', name: 'Royal Mail Click & Drop' },
  { key: 'SEUR', name: 'SEUR' },
  { key: 'UPS', name: 'UPS' },
  { key: 'USPS', name: 'USPS' },
  { key: 'Whistl', name: 'Whistl' },
  { key: 'Yodel', name: 'Yodel' },
  { key: 'YodelCorporate', name: 'Yodel Corporate' },
];

export const HEYVOILA_FIELDS: FieldDefinition[] = [
  {
    key: 'tracking_codes',
    label: 'Tracking Code(s)',
    section: 'Required / Tracking',
    required: true,
    description: 'Tracking number(s). Multiple can be separated by commas or semicolons.',
    example: '123456789 or JD0146000000',
    aliases: [
      'tracking',
      'tracking_code',
      'tracking_codes',
      'tracking_number',
      'tracking_no',
      'tracking_id',
      'waybill',
      'consignment',
      'consignment_number',
      'consignment_no',
      'awb',
      'barcode',
      'parcel_number',
      'package_tracking',
    ],
  },
  {
    key: 'courier_key',
    label: 'Courier Carrier (Row-level override)',
    section: 'Required / Tracking',
    required: true,
    description: 'Courier for this row (e.g. DPD, DHL, RoyalMail). If unmapped, uses the File-Level Courier selected above.',
    example: 'DPD / DHL / AmazonShipping',
    aliases: [
      'courier',
      'courier_key',
      'courier_code',
      'carrier',
      'carrier_name',
      'shipping_provider',
      'shipper',
      'courier_name',
      'service_carrier',
    ],
  },
  {
    key: 'reference',
    label: 'Reference (Order / Shipment ID)',
    section: 'Shipment Info',
    required: false,
    description: 'Primary reference identifier such as your internal order number.',
    example: 'ORD-109283',
    aliases: [
      'reference',
      'order_id',
      'order_number',
      'order_no',
      'ref',
      'reference_1',
      'order_ref',
      'invoice_number',
      'invoice_no',
      'po_number',
    ],
  },
  {
    key: 'reference_2',
    label: 'Reference 2 (Secondary Ref)',
    section: 'Shipment Info',
    required: false,
    description: 'Secondary reference number or customer identifier.',
    example: 'CUST-88392',
    aliases: [
      'reference_2',
      'ref_2',
      'ref2',
      'secondary_reference',
      'customer_reference',
      'client_reference',
      'ext_id',
      'external_id',
    ],
  },
  {
    key: 'request_id',
    label: 'Request ID',
    section: 'Shipment Info',
    required: false,
    description: 'Numeric or unique ID for tracking your batch request.',
    example: '123456789',
    aliases: ['request_id', 'req_id', 'job_id', 'batch_id', 'id'],
  },
  {
    key: 'collection_date',
    label: 'Collection Date',
    section: 'Shipment Info',
    required: false,
    description: 'ISO formatted date/time when package was collected (e.g. 2026-09-22T16:30:00Z).',
    example: '2026-09-22T16:30:00Z',
    aliases: [
      'collection_date',
      'pickup_date',
      'ship_date',
      'dispatched_at',
      'shipped_at',
      'date_shipped',
      'dispatch_date',
      'created_at',
    ],
  },
  {
    key: 'ship_to_name',
    label: 'Recipient Full Name',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'Full name of the recipient.',
    example: 'Laura Maura',
    aliases: [
      'ship_to_name',
      'recipient_name',
      'customer_name',
      'contact_name',
      'name',
      'full_name',
      'receiver_name',
      'addressee',
      'buyer_name',
    ],
  },
  {
    key: 'ship_to_phone',
    label: 'Recipient Phone',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'Recipient phone number for SMS tracking updates.',
    example: '+44 7700 900077',
    aliases: [
      'ship_to_phone',
      'phone',
      'phone_number',
      'mobile',
      'telephone',
      'tel',
      'cell',
      'recipient_phone',
      'contact_phone',
    ],
  },
  {
    key: 'ship_to_email',
    label: 'Recipient Email',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'Recipient email address for tracking notifications.',
    example: 'support@buyer.com',
    aliases: [
      'ship_to_email',
      'email',
      'email_address',
      'recipient_email',
      'customer_email',
      'buyer_email',
      'contact_email',
    ],
  },
  {
    key: 'ship_to_company_name',
    label: 'Recipient Company',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'Company name if delivering to a business.',
    example: 'Acme Logistics Ltd',
    aliases: [
      'ship_to_company',
      'ship_to_company_name',
      'company',
      'company_name',
      'business_name',
      'organization',
      'organisation',
    ],
  },
  {
    key: 'ship_to_address_1',
    label: 'Address Line 1',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'Street address line 1.',
    example: '123 High Street',
    aliases: [
      'ship_to_address_1',
      'address_1',
      'address_line_1',
      'address1',
      'street_address',
      'street',
      'address',
      'line_1',
    ],
  },
  {
    key: 'ship_to_address_2',
    label: 'Address Line 2',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'Apartment, suite, unit, or building.',
    example: 'Suite 4B',
    aliases: [
      'ship_to_address_2',
      'address_2',
      'address_line_2',
      'address2',
      'line_2',
      'apartment',
      'suite',
      'unit',
    ],
  },
  {
    key: 'ship_to_address_3',
    label: 'Address Line 3',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'Additional address / locality info.',
    example: 'Industrial Park',
    aliases: ['ship_to_address_3', 'address_3', 'address_line_3', 'address3', 'line_3'],
  },
  {
    key: 'ship_to_city',
    label: 'City / Town',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'Destination city, town or suburb.',
    example: 'London',
    aliases: ['ship_to_city', 'city', 'town', 'locality', 'suburb', 'destination_city'],
  },
  {
    key: 'ship_to_county',
    label: 'County / State / Province',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'County, state, region, or province.',
    example: 'Greater London',
    aliases: [
      'ship_to_county',
      'county',
      'state',
      'province',
      'region',
      'state_code',
      'state_or_province',
    ],
  },
  {
    key: 'ship_to_postcode',
    label: 'Postcode / ZIP',
    section: 'Recipient (Ship To)',
    required: false,
    description: 'Postal code or ZIP code.',
    example: 'SW1A 1AA or 90210',
    aliases: [
      'ship_to_postcode',
      'postcode',
      'postal_code',
      'zip',
      'zip_code',
      'zipcode',
      'post_code',
      'pin',
      'pincode',
    ],
  },
  {
    key: 'ship_to_country_iso',
    label: 'Country ISO Code (2-letter)',
    section: 'Recipient (Ship To)',
    required: false,
    description: '2-letter country code (ISO 3166-1 alpha-2, e.g. GB, US, DE, FR, SE).',
    example: 'GB',
    aliases: [
      'ship_to_country_iso',
      'country_iso',
      'country_code',
      'country',
      'country_iso2',
      'iso_country',
      'destination_country',
    ],
  },
  {
    key: 'courier_specific_shipment_ids',
    label: 'Courier Specific Shipment ID(s)',
    section: 'Courier Specifics',
    required: false,
    description: 'Optional shipment IDs required for some couriers (e.g. Amazon Shipping).',
    example: '123456',
    aliases: [
      'courier_specific_shipment_ids',
      'shipment_ids',
      'amazon_shipment_id',
      'external_shipment_id',
    ],
  },
];
